### ISSUE TITLE
Feature request: Allow us to hide one or both rows of "info items"

### ISSUE THREAD

**Issue by BigMacAdmin** [root3nl/SupportApp#102]
Per this thread on Slack, I'm making an issue for this. https://macadmins.slack.com/archives/C02JD4WCXLH/p1670432174126869

While designing our UI/UX I was asked if we can just disable the "info" boxes, rather than use the default options there. I didn't see it as a feature, so putting it here for consideration.

**Comment by jordywitteman** [comment]
Will be added in v2.5

**Comment by jordywitteman** [comment]
You can now use `HideFirstRowInfoItems`, `HideSecondRowInfoItems ` and `HideThirdRowInfoItems` to hide rows with info items
