### ISSUE TITLE
Bug Report - Badge for macOS version update available not refreshing

### ISSUE THREAD

**Issue by xirianlight** [root3nl/SupportApp#103]
Hey folks, getting a report from a client that all their Macs are still showing the red badge for update being available after running the update to 12.6.2. Is there a CLI command or something we can push to devices to force this to reindex?

![Screen Shot 2022-12-14 at 5 35 20 PM](https://user-images.githubusercontent.com/3473651/207921959-05da47d6-51d9-4b60-82a4-53442115a6bd.png)

**Comment by xirianlight** [comment]
From a Slack discussion, it looks like this is related to the Ventura delta upgrade being detected by the softwareupdate binary, even if there's an MDM configuration present to defer it. Jordy suggested a possible key to `IgnoreMajorVersions`, which would be a spectacular solution to differentiate the availability of delta upgrades from the usual software updates.

**Comment by jordywitteman** [comment]
Hi all!

Please test this prerelease version of 2.4.3: https://github.com/root3nl/SupportApp/releases/tag/v2.4.3-beta

Curious to hear your feedback!

**Comment by xirianlight** [comment]
Looks great - here's a before and after applying the new key using:
<key>HideMajorUpdates</key>
<true/>
<img width="454" alt="Before" src="https://user-images.githubusercontent.com/3473651/208973260-18407b83-5263-469c-8776-6182353f3bdf.png">
<img width="454" alt="After" src="https://user-images.githubusercontent.com/3473651/208973273-f9646bfe-0323-46b5-800e-203148c0205b.png">

**Comment by blockcham** [comment]
@xirianlight agreed, seems to working well.  I just added the following to the current JSON Schema and deployed both pre-release version and profile and the badge goes away.

`    "HideMajorUpdates": {
      "title": "Hide major updates",
      "description": "Hide major updates",
      "type": "boolean",
      "options": {
        "enum_titles": [
          "Hide",
          "Show"
        ],
        "infoText": "Key name: HideMajorUpdates"
      },
      "links": [
        {
          "rel": "Documentation",
          "href": "https://github.com/root3nl/SupportApp"
        }
      ]
    },`

@jordywitteman can't image so but is there anything else specific that you need tested?

**Comment by xirianlight** [comment]
Resolved in 2.4.3
