### ISSUE TITLE
RSR OS Support

### ISSUE THREAD

**Issue by macmule** [root3nl/SupportApp#114]
Hi folks,

The [ProcessInfo class](https://developer.apple.com/documentation/foundation/processinfo), does not return details on an RSR.. and looking at the following, this seems to be what you're using to derive the OS version: https://github.com/root3nl/SupportApp/blob/03ad9da19cf374ce6447e1319c956b7663b6888c/src/Support/ComputerInfo.swift#LL26C1-L29C5

You can get the RSR details from sw_vers, so might need to shell out:

```
$ /usr/bin/sw_vers -productVersion
13.3.1
$ /usr/bin/sw_vers -productVersionExtra
(a)
```

**Comment by jordywitteman** [comment]
Thanks @macmule! Didn't know about -productVersionExtra argument. Not the preferred way but as long as Apple doesn't provide it in the native frameworks this is probably the only way and append the output to the version string. Let me put in on the roadmap for v2.5 which we hope to release in June
