### ISSUE TITLE
Local variables

### ISSUE THREAD

**Issue by Melvin-P-NL** [root3nl/SupportApp#125]
Would be great if it’s possible to use local computer information for Title and other texts. I would like to show the computer name there, but preferably independent from Jamf Pro computer inventory, as like the InfoItems work.

Maybe some of the options for InfoItems could work as a local variable, so you can put it in a string, like;
%ComputerName%
%MacOSVersion%
%ExtensionA%
%ExtensionB%

An item I would like to be added and handled the same way, is the current logged in user (full name, eventually system name). Could do that with an extension, but then I still need the requested feature to use it in the Title. Then I could set “Hello, %UserName%!” as the Title, returning “Hello, John!”.

One more thing, a gimmick to make SupportApp more personal. Maybe do something with parts of the day. Let’s say 0-5 is night, 5-12 is morning, 12-18 is afternoon, 18-24 is evening. A variable like %DayPart% could return “(Good )night, -morning, -afternoon or -evening”, so the string might be “(Good )%DayPart%, %UserName%”, resulting in “Good morning, John!”.

Even wilder would be if you could set variables for this, with configuration keys like DayPartNight, DayPartMorning, DayPartAfternoon and DayPartEvening. Then even “Howdy, John!” and “It’s bedtime, John…” are options.

**Comment by jordywitteman** [comment]
Local variables are added in v2.5: https://github.com/root3nl/SupportApp#built-in-local-variables. The other suggestions with the day parts is probably a bridge too far but may be scripted locally.
