### ISSUE TITLE
StatusBarIcon	color not matching

### ISSUE THREAD

**Issue by mikeknight85** [root3nl/SupportApp#139]
If a custom StatusBarIcon is set, the color of the selected file is ignored and inverted. 

<img width="113" alt="Screenshot 2023-08-10 at 15 11 06" src="https://github.com/root3nl/SupportApp/assets/8047701/99b44703-2aeb-47e9-b2a0-bf214bdbe1e9">

**Comment by jordywitteman** [comment]
Hi @mikeknight85 this is by design and follows [Apple's HIG](https://developer.apple.com/design/human-interface-guidelines/the-menu-bar#Menu-bar-extras) to make sure the menu bar icons always looks great, light/dark mode and provide contrast on top of wallpaper colors.
