### ISSUE TITLE
Custom company logo not working

### ISSUE THREAD

**Issue by typeraj** [root3nl/SupportApp#14]
I can't get the custom logo to stick. Tried placing it in a few different locations (and updating the path in the config profile), but the app still shows the original green logo. What am I missing? 

Loving the app, thank you for sharing.

**Comment by jordywitteman** [comment]
Hi @typeraj, where did you put the image and could perhaps share a bit of the config file? Thanks!

**Comment by typeraj** [comment]
Hi @jordywitteman, sure, currently I have it `/Library/Application\ Support/` but I've also tried putting it in `/Users/Shared` with no luck. Here is a snippet from the PLIST file:



    <key>Title</key>
    <string>SiteMinder IT Support</string>
    <key>Logo</key>
    <string>/Library/Application\ Support/SiteMinder/brandingimage.png</string>
    <key>LogoDarkMode</key>
    <string>/Library/Application\ Support/SiteMinder/brandingimage.png</string>

**Comment by jordywitteman** [comment]
Please try removing the backslash between Application and Support, so '/Library/Application Support/'. '/Users/Shared' probably doesn't work because of the sandbox. Hope it works now!

**Comment by typeraj** [comment]
Yes, it's working now. Thanks!
