### ISSUE TITLE
MenuBar icon only in greyscale?

### ISSUE THREAD

**Issue by sudodaemon** [root3nl/SupportApp#142]
I have added a menu bar icon, but even thought the PNG file is in color it pulls up as greyscale. Is there a setting I am missing or is this expected behavior?

**Comment by meta-github** [comment]
Renderlng the icon as grayscale is currently hardcoded in the app, iirc. I think, this is to ensure that the alert flags are properly visible.

To display our company logo correctly, I have disabled the option to do the grayscaling as and changed the colors of the alerts.

**Comment by sudodaemon** [comment]
So wait, is there a way to disable the grayscale option? First you said its hard coded, then you said you disabled it...

**Comment by meta-github** [comment]
Yes, I disabled it by changing the source code.

**Comment by sudodaemon** [comment]
Could you point me in the right direction? I've been looking through a bunch of files but can't find anything relating to color other than dark mode, light mode, etc. Can't find anything relating to the menubar / notification icon.

**Comment by meta-github** [comment]
Look at src/Support/AppDelegate.swift:

uncomment the line `button.image?.isTemplate = true` and (optionally) change these lines for other colors: `leStatusItemBadgeView(frame: .zero, color: .systemRed)` and `StatusItemBadgeView(frame: .zero, color: .systemOrange)`.

**Comment by sudodaemon** [comment]
Just in case anybody else is trying to do this, I found that the line wasn't commented out, it was just listed as True, so setting it to False was the key.

So it should be 

button.image?.isTemplate = false

Maybe it was a typo on your end? Doesn't matter, point is, it fixed my issue and I am happy. Icon is in color now and it's been pushed out to all the computers I manage.

**Comment by jordywitteman** [comment]
Will close this issue as it is resolved by recompiling after code changes. We feel we should not provide the non-template option in the release version to maintain the native look and feel of the menu bar icon. Generally speaking, it should blend in nicely with the rest of the icons and adapt to changes like wallpaper and light/dark mode.
