### ISSUE TITLE
Two Support.app processes running at same time

### ISSUE THREAD

**Issue by EdBascom** [root3nl/SupportApp#143]
what is the launch mechanism for starting the support app - I have two apps running simultaneously. killing one and restarting the computer just starts up two processes again.

**Comment by jordywitteman** [comment]
Hi @EdBascom if you use the regular PKG installer, it included a LaunchAgent to automatically launch the app and keepalive (if user would close it). There is no need to programmatically launch the app using scripts/commands. The ZIP containing the .app bundle does not include this so this is a suitable solution if you want to create your own launch mechanism. Please check here for more info: https://github.com/root3nl/SupportApp#download
