### ISSUE TITLE
is:open label:"help wanted" - Issue -  crash report support helper running as root 

### ISSUE THREAD

**Issue by Ninjastic-Ninja** [root3nl/SupportApp#147]
<img width="1050" alt="support_crash" src="https://github.com/root3nl/SupportApp/assets/39200937/3fd9e10f-8b09-4c9b-8352-ee0b3e2a7149">

I see crash report support helper running as root , wondering what that could be ?

I don't see any crash happening and it's running as root

**Comment by Ninjastic-Ninja** [comment]
Being Curious here I reboot my Mac and open support app . Battery was drained and plugged power back , I see crash report support helper app running as root.

Found this as process crashing  

CrashReporterSupportHelper CrashReporterSupportHelper   (0, libsystem_malloc.dylib, 0x0000000000003f44)
Support  Support   (2.5, libsystem_secinit.dylib, 0x0000000000002214)

Support Support   (2.5, Support, 0x0000000000032bc8)

<img width="1177" alt="Screenshot 2023-09-08 at 4 41 50 PM" src="https://github.com/root3nl/SupportApp/assets/39200937/166a34da-a844-49ff-87eb-7025237b2297">

**Comment by Ninjastic-Ninja** [comment]
@jordywitteman - Looking for your inputs . Could you let me know if you see anything like this happening at your end . I'm running support app in M2 mac

**Comment by jordywitteman** [comment]
Hi @Ninjastic-Ninja This process is Apple-owned and not related to the Support App or SupportHelper. It lives here: `/System/Library/CoreServices/CrashReporterSupportHelper`. I don't think this is anything to investigate here and just a coincidence with processes with similar names
