### ISSUE TITLE
Minor Query

### ISSUE THREAD

**Issue by danielnovello** [root3nl/SupportApp#15]
When linking a button to a Slack DM, it does not work. It opens the Slack app, but not the DM for the user in the link.
_If you copy paste the same link in the browser, it opens Slack and starts a new DM for the user in the link. They way I expected to work._

Sandboxing not allowing it?

**Comment by jordywitteman** [comment]
Hi @danielnovello interesting use case! Have not worked with this before but will try and see if I can help. Are you using the URL or Command option in the config profile?

**Comment by danielnovello** [comment]
Hi there, Im using the URL (E.G. `https://me.slack.com/team/U0218Q3KVCU`)
It does work if you copy and paste into the browser.
https://slack.com/intl/en-za/help/articles/360003827751-Create-a-link-to-a-members-profile-

**Comment by martinvandiemen** [comment]
@danielnovello could you try URL option and use slack://channel?team={TEAM_ID}&id={CHANNEL_ID}. More information can be found here: https://api.slack.com/reference/deep-linking#open_a_channel

**Comment by danielnovello** [comment]
Unfortunately that does not work

**Comment by martinvandiemen** [comment]
I've just tested this. When I use my TEAM_ID and CHANNEL_ID it works as expected. Could you try installing Slack outside the Mac App Store and check if it's working?

**Comment by danielnovello** [comment]
Using the link like that does work, however using a URL with **&** character does not appear to work in a mobileconfig file

**Comment by martinvandiemen** [comment]
Which MDM server do you use?

**Comment by danielnovello** [comment]
Jamf. I wrapped it in a CDATA  `E.G. <![CDATA[slack://channel?team=T02930WY7&id=D027CF89145]]>` and the profile works. However, the link within the Menubar app still does not. It only opens the Slack app, not the DM.
Did you manage to get it to work?

**Comment by martinvandiemen** [comment]
Yes, I have.

You should replace & with &amps; like this:
`<string>slack://channel?team=T02930WY7&amp;id=D027CF89145</string>`
CDATA should not be needed.

Secondly. Why aren't you using our [Jamf Pro custom JSON schema](https://github.com/root3nl/SupportApp/blob/master/Jamf%20Pro%20Custom%20Schema/Jamf%20Pro%20Custom%20Schema.json) which makes configuring the Support App really easy in Jamf.

**Comment by salesloftcb** [comment]
> Yes, I have.
> 
> You should replace & with &amps; like this:
> `<string>slack://channel?team=T02930WY7&amp;id=D027CF89145</string>`
> CDATA should not be needed.
> 
> Secondly. Why aren't you using our [Jamf Pro custom JSON schema](https://github.com/root3nl/SupportApp/blob/master/Jamf%20Pro%20Custom%20Schema/Jamf%20Pro%20Custom%20Schema.json) which makes configuring the Support App really easy in Jamf.

What should the format look like with the JSON custom schema in Jamf? Trying to deeplink to an app and I know the URL works, but this is what I've got in the field and the app errors out:

`slack://app?team=XXXXX&amp;id=XXXXX&amp;tab=home`

![image](https://user-images.githubusercontent.com/44003383/124848537-10209e80-df6b-11eb-9a16-b300cbaeb013.png)

**Comment by jordywitteman** [comment]
Hi @salesloftcb did you get this to work? We've been using it successfully for a while now with just this in the JSON manifest: `slack://channel?team=TEAM_HERE&id=ID_HERE`

**Comment by jordywitteman** [comment]
Closing this one as it works as expected in our testing.
