### ISSUE TITLE
Emojis don't work in footer

### ISSUE THREAD

**Issue by Konack** [root3nl/SupportApp#155]
When adding an emoji to the footer option Jamf converts the emoji to a "?" after saving the profile.

Support App Version: 2.5.1
Jamf Pro Version: 11.0.1

**Comment by martinvandiemen** [comment]
Can you share your footer so we can check? I can't reproduce this.

**Comment by Konack** [comment]
I went to check this again on version Version11.1.1 of Jamf Pro and it seems to have resolved itself.
