### ISSUE TITLE
PasswordExpiryLimit only shows "Never Expires"

### ISSUE THREAD

**Issue by XAGSolutions** [root3nl/SupportApp#158]
```
<key>InfoItemFive</key>
<string>Password</string>
<key>PasswordExpiryLimit</key>
<integer>15</integer>
<key>PasswordType</key>
<string>Apple</string>
<key>PasswordLabel</key>
<string>Mac Password</string>
```
								
<img width="188" alt="image" src="https://github.com/root3nl/SupportApp/assets/46761745/f80cd3aa-9dc2-4386-8648-c60c94f6e890">

Can someone help me understand why this is not reflecting an expired password?

**Comment by jordywitteman** [comment]
Hi @XAGSolutions where and how did you configure a password policy? Using a passcode configuration profile?

**Comment by XAGSolutions** [comment]
There is not an existing Policy.  I was under the impression that the:
`<key>PasswordExpiryLimit</key>
<integer>15</integer>`

WAS the limit.

**Comment by jordywitteman** [comment]
Hi @XAGSolutions no the app looks at the local configured password policy and the `PasswordExpiryLimit` is intended to warn the user x days before the password expires following local macOS policy. Hope it now works for you.
