### ISSUE TITLE
App Updates via App Catalog not disappearing after update

### ISSUE THREAD

**Issue by wkneppersR3** [root3nl/SupportApp#167]
In beta release 2.6 (20) it seems the App Updates part won't update after the App Catalog updated an app. The countdown works, the App Catalog updates the app, but the Support app still shows there's an update available. After relaunching the app, the notification/update disappears.

See attached screenshots. 
<img width="454" alt="Screenshot 2024-04-15 at 09 38 12" src="https://github.com/root3nl/SupportApp/assets/101091286/753ea71d-715e-462d-97e6-2c1091481d2c">
<img width="414" alt="Screenshot 2024-04-15 at 09 38 17" src="https://github.com/root3nl/SupportApp/assets/101091286/b8282616-87b2-4c11-8dfc-af1744a39be5">

**Comment by jordywitteman** [comment]
@wkneppersR3 this issue is resolved with a server-side fix
