### ISSUE TITLE
Issues Running Script from Support.app

### ISSUE THREAD

**Issue by shMorganson** [root3nl/SupportApp#168]
I am trying to use a tile to run a script with the Support.app and when I put /Library/Application Support/company/file.sh the script doesn't run from the the Support.app. Nothing will happen. The file is set to execute and if I call it directly it runs without issues.

**Comment by wakco** [comment]
Known issue, has two parts, first try escaping the space i.e. `/Library/Application\ Support/company/file.sh`, then for prior to version 2.6 (which is still in beta),  if escaping the space doesn't help. try installing the SupportHelper. Lastly, as a just in case, make sure file.sh has the execute permission (that is, when viewing the file with `ls -l /Library/Application\ Support/company/file.sh`, it should at least have read and execute permissions like r-x-rxr-x)

**Comment by jordywitteman** [comment]
Hi @shMorganson yes please try escaping the spaces in the file path. This will no longer be necessary with v2.6 and both formats will be supported.
