### ISSUE TITLE
Allow defaults write in PrivilegedScript

### ISSUE THREAD

**Issue by phillscholl** [root3nl/SupportApp#172]
Now with the Support 2.6 App which is currently in BETA status and the built-in support for executing scripts with elevated privileges, would it be nice to have the ability to use the defaults write function in theses privileges scripts.

**Comment by phillscholl** [comment]
let me explain it: with the ability to use defaults write i could dynamically change the icon or text on "Second Row Right"  which would make the support app more dynamic. Or at lease give me the opportunity to use my own variables in scripts to set this.

**Comment by wakco** [comment]
I'm pretty sure that's the whole point in forcing a script, to make it easier to allow all of that.

It sounds like to me you were effectively writing a script in the command using ;'s between each command, forcing the script seems to be a better choice, remember the config for identifying the script to run (and formerly command), never could be changed dynamically (outside of an MDM pushed update to the config profile), and can only be set by the MDM supplied config profile.

**Comment by wakco** [comment]
You still can, so long as it's not configured by the MDM provided config profile. Aside from the Privileged Script settings everything can be scripted, so long as they are not defined in the MDM provided config profile. So as long as you define the "Second Row Right" button, without defining its icon, label, or hover-over label, those aspects of the button can still be changed.

**Comment by phillscholl** [comment]
Oh, that's right. I hadn't even thought about that. So this issue can be closed as it works as desired. Thank you very much.
