### ISSUE TITLE
Crashes at launch after 2.2 install

### ISSUE THREAD

**Issue by xirianlight** [root3nl/SupportApp#18]
I tried installing 2.2 on two devices - my main work machine and a Big Sur VM, both running 11.3.1. Works flawlessly on my main machine, but on the VM, the app crashes every time I click the menu bar icon. After the crash, it appears to reload, then clicking the button crashes it again.

I uninstalled/reinstalled it to see if the .pkg had misfired, no change. I removed all MDM configs for the app, no change. Tried uploading a new mobileconfig that included the badge for uptime, no change. Reboot, no change.

Attaching crash report - any idea on what's causing this? If there's a fix, I can build it into my deployment or uninstallation script as needed.

[supportMenu2.2_crashLog.txt](https://github.com/root3nl/SupportApp/files/6585920/supportMenu2.2_crashLog.txt)

**Comment by jordywitteman** [comment]
Hi @xirianlight we were able to reproduce and it turns out the crash is related to a query to get the Mac's introduction year. A fix will come soon. As a workaround, you could simulate a 'real world' serial number in the VM's config file

**Comment by jordywitteman** [comment]
@xirianlight v2.2.1 was just released and I believe the crash is fixed when no serial number is set.
