### ISSUE TITLE
Feature Request - set alert icon to StatusBarIcon

### ISSUE THREAD

**Issue by xirianlight** [root3nl/SupportApp#19]
Love the new popup that occurs when you click on the device uptime to get a little disclaimer about rebooting your Mac. Would it be possible to have a key that sets the icon that appears there to equal the StatusBarIcon value instead of the default app icon? I've been trying to replace the app icon for ages and not had any success, so my users would be seeing it for the first time in that popup. Thanks!

**Comment by jordywitteman** [comment]
Hi @xirianlight currently SwiftUI does not seem to support putting a custom icon in an Alert an always shows the app icon on macOS. We will however look into the option to change the app icon. Also, we are excited to see what Apple has prepared for us in SwiftUI 3 at WWDC21 next week :)

**Comment by avenjamin** [comment]
I'm seeing this issue too for the "Error Alert" popup
Is it possible to at least remove the default green colour that I'm seeing behind the life ring?
Cheers

**Comment by sidbena** [comment]
Perhaps one could render a custom view with an interface much like an alert, thereby allowing an `Image(systemName: "<custom SF Symbol name>")`? Just a thought.

**Comment by xirianlight** [comment]
Anyone following this, check out https://github.com/mklement0/fileicon - I was able to use this to change the application icon, which then changes the icon in this alert! It's a really easy to use binary and I could feed it a .icns file in no time.

**Comment by jordywitteman** [comment]
As lots of admins are requesting a custom app icon, this is one of the top priorities for an upcoming release! Thanks for the feedback!

**Comment by jordywitteman** [comment]
In version 2.3 we've added the key **NotificationIcon** to modify the alert icon and also in the about window. Will not change the app icon due to App Sandbox but we figured this is less important.
