### ISSUE TITLE
How to grep the jamf self-service available updates 

### ISSUE THREAD

**Issue by mani2care** [root3nl/SupportApp#193]
How to grep the jamf self-service available updates

**Comment by wakco** [comment]
Uhm, while I hope for you someone involved with SupportApp might be able to help, this question is probably better asked on the Jamf Nation forums [https://community.jamf.com/](https://community.jamf.com/), or the #jamfnation channel on the MacAdmins Slack.

**Comment by jordywitteman** [comment]
@mani2care please try asking with more details what you want to achieve in the suggested channels. As this is not an issue for the Support App, we'll close it.
