### ISSUE TITLE
"Support" differs from previously opened versions. Are you sure you want to open it?

### ISSUE THREAD

**Issue by martinwiden** [root3nl/SupportApp#198]
After reinstalling macOS (15.0.1) and deploying Support.app (version 2.6) via a policy with a .pkg in Jamf Pro (11.9.1), i get a popup with the message:
""Support" differs from previously opened versions. Are you sure you want to open it?"

I read this thread on Slack: https://macadmins.slack.com/archives/C02JD4WCXLH/p1726652165038599 that several people are having the same issue. I saw that Jordy answered in a comment but I didn't find any issues regarding this so I took the liberty to create one for you!

![Image 2024-10-23 at 14 17](https://github.com/user-attachments/assets/f7cd2520-0a6f-400a-9799-36af35dcd0c9)

**Comment by jordywitteman** [comment]
Is there any difference for macOS 15.1 devices? I haven’t seen the issue myself unfortunately but it appears to be related to sandboxed apps and some increased security rules in macOS 14+ to prevent other apps from accessing the sandbox container: https://developer.apple.com/documentation/security/accessing-files-from-the-macos-app-sandbox, https://lapcatsoftware.com/articles/2023/6/1.html. However, it doesn’t make sense to me why it should prompt during the initial deployment of the app. Perhaps you are seeing this with other sandboxed apps as well? Trying to figure out if I need to fix something or if it’s a macOS bug which hopefully gets resolved

**Comment by jordywitteman** [comment]
@martinwiden any news on this for macOS 15.1+ enrollments?

**Comment by BigMacAdmin** [comment]
I just experienced this issue on macOS 15.4 RC2, fresh OS install and fresh Support App install.

Will open a new issue or report back if I can repeat.
