### ISSUE TITLE
Feature Request - run command

### ISSUE THREAD

**Issue by xirianlight** [root3nl/SupportApp#2]
Would it be possible to have an option for buttons to run a bash or zshell command? I'm hoping to launch an app with an argument supplied, but can't given the need to list the app by bundle ID rather than supply the "open /Applications/myApp.app/Contents/MacOS --info" command. 

Also, tried to point the app to "/System/Library/PreferencePanes/SoftwareUpdate.prefPane" (set as Bundle ID "com.apple.preferences.softwareupdate"), but it threw an error. Thanks, love this project!

**Comment by martinvandiemen** [comment]
Hi @xirianlight,

Thanks for your feedback! We'll look into the command request. Could you let me know if you want to run this as root or user?

To open Software Update please use: x-apple.systempreferences:com.apple.preferences.softwareupdate

**Comment by jordywitteman** [comment]
Hi @xirianlight,

You could also use something like this with URL as type: file://System/Library/PreferencePanes/Accounts.prefPane
Not all System Preference panes can be opened using x-apple.systempreferences, so this could be a better option.

**Comment by Karl941** [comment]
> Would it be possible to have an option for buttons to run a bash or zshell command? I'm hoping to launch an app with an argument supplied, but can't given the need to list the app by bundle ID rather than supply the "open /Applications/myApp.app/Contents/MacOS --info" command.

+1 👍 if possible!

**Comment by xirianlight** [comment]
> Hi @xirianlight,
> 
> Thanks for your feedback! We'll look into the command request. Could you let me know if you want to run this as root or user?
> 
> To open Software Update please use: x-apple.systempreferences:com.apple.preferences.softwareupdate
> Also, the Type value should be URL.

I'll try that method for Software Updates, thank you! I'd rather run the command as root since I can always su into the user-space if I need to, but not in the other direction. If it's a security concern or other development nightmare to have root access from Support.app, totally understood.

**Comment by xirianlight** [comment]
Update for posterity's sake - using the file:// item listed above did not work, but the xprefs command did (for Software Update). Thanks again for the assist, looking forward to seeing if the option to run a command (and solving how to save that in the .mobileconfig) on a button press shakes out.

**Comment by Karl941** [comment]
Can't wait to see that execution command feature!

**Comment by jordywitteman** [comment]
@xirianlight thanks for testing! Seems like I posted two forward slashes instead of one. Just tested and verified to open the Accounts prefpane with: file:/System/Library/PreferencePanes/Accounts.prefPane

**Comment by xirianlight** [comment]
Thanks for getting this added in 2.1! And thanks for clarifying in the documentation that the script will be run in user-space without root privileges.
