### ISSUE TITLE
ConfigProfile example of adding IP address 

### ISSUE THREAD

**Issue by GenoMyb** [root3nl/SupportApp#20]
Can you kindly share what the config profile will look like to add I Address

**Comment by jordywitteman** [comment]
Hi @GenoMyb, check the **Info items** table in the configuration section. The keys are called **InfoItemOne** etc and can be one of the six available options mentioned in the same table.

**Comment by GenoMyb** [comment]
Hello , Hope you are well 
i tried to add the string InfoItemOne and set it to network
and it doent it work
