### ISSUE TITLE
Feature Request - Show Jamf Connect Password Expiry Time

### ISSUE THREAD

**Issue by cdog2020** [root3nl/SupportApp#22]
It would be rad to not only have the custom link to password change as requested by AndersTao, but it would also be rad to have it show when the password expires for Jamf Connect.  

Regardless, love the app.  Great work!

**Comment by martinvandiemen** [comment]
We'll use Mac Password only for local and AD passwords. For other (password) solutions we would recommend to use that (menubar) tool.
