### ISSUE TITLE
Feature Request - Customizable IP address (VPN)

### ISSUE THREAD

**Issue by chastinker** [root3nl/SupportApp#24]
Love the new features in 2.2. 

Noticed that when deploying that new Network InfoItem when deployed to a Mac that is using a VPN client it is showing the localized address versus the VPN Client Address. We have a zsh command that can pull the accurate IP address every time. There does not seem to be an InfoItemType preference to allow for a command. Requesting a way to use said command to display the IP address we'd want in that ItemInfo panel. 

Thank you again!

**Comment by jordywitteman** [comment]
Thanks @chastinker!

Interesting use case! We have put in on the backlog and will look into it

**Comment by martinwen1990** [comment]
Thanks for the great app!

We would also appreciate the VPN IP address view. Thank you very much.

**Comment by martinwen1990** [comment]
Is there a release date here yet? :)

**Comment by martinvandiemen** [comment]
Yes, you'll be able to do this in the upcoming release. We're release this in the next month(s).

**Comment by martinwen1990** [comment]
> Yes, you'll be able to do this in the upcoming release. We're release this in the next month(s).

That sounds great! We think the support app is totally awesome and would like to see the feature requests already made. Can you tell us which requests you would like to implement? Thank you very much!

**Comment by jordywitteman** [comment]
Please look into the new Support App Extension possibilities to show any information you can get using scripts. The new SupportHelper may be helpful here to fetch new info on every appearance of the app. We'll mark this issue as closed.
