### ISSUE TITLE
Feature Request - Support NoMAD/Custom Data for password expiry

### ISSUE THREAD

**Issue by smithjw** [root3nl/SupportApp#30]
A lot of organisations use NoMAD and it would be great to support it for Password Expiry notifications. Currently you pull in either Local Password Expiry or AD, I propose you also support NoMAD which has the following field to pull data from:

`defaults read com.trusourcelabs.NoMAD LastPasswordExpireDate`

This results in the response `2021-07-24 23:02:04 +0000`. In terms of resetting the password, you can run the following command `nomad://passwordchange` which will open the NoMAD Change Password window as documented here 👉 https://nomad.menu/2017/03/09/apple-events/.

You might ask why I would deploy Support App and have it show me the dates till password expiry if I already have NoMAD? Well in this case I would still have NoMAD launched at login, but run it with the preference `LightsOutIKnowWhatImDoing` so that the icon is no longer displayed

If it is too complex to add native support for this. Allow admins to configure a button with the ability to display a number pulled from the local disk.

**Comment by lonit-was** [comment]
Upvote this feature, including support for Jamf Connect password expiration from com.jamf.connect.state.plist (defaults read com.jamf.connect.state ComputedPasswordExpireDate)

**Comment by Burnhamt256** [comment]
I would like to see that feature as well.

**Comment by FOHAMMR** [comment]
This feature would be very helpful working for Jamf Connect.

**Comment by jmahlman** [comment]
This would be a great feature.

**Comment by jordywitteman** [comment]
Other sources for password expiration is planned for the next release: Jamf Connect, Kerberos SSO Extension and NoMAD. We'll release a beta soon!

**Comment by smithjw** [comment]
Thanks for the update!

**Comment by smithjw** [comment]
@jordywitteman Any word when we'll see this beta?

**Comment by jordywitteman** [comment]
Jamf Connect, Kerberos SSO Extension and NoMAD are now available in v2.4
