### ISSUE TITLE
Feature Request: Show last inventory update and policy check-in

### ISSUE THREAD

**Issue by jaedwards24** [root3nl/SupportApp#39]
Could tiles be set to show the last Jamf inventory update and policy check-in based on what's in jamf.log? Possibly reformat and calculate based on this? 
`grep "Checking for policies triggered by \"recurring check-in\"" /private/var/log/jamf.log | tail -n 1 | awk '{print $2,$3,$4}'`
`grep "Executing Policy [NAME OF INVENTORY UPDATE POLICY TO MONITOR]" /private/var/log/jamf.log | tail -n 1 | awk '{print $2,$3,$4}'`

If these have not happened in a specified limit period (similar to Uptime Days Limit), notify for some remediation. Perhaps clicking the tile could kick off a Self Service policy using `open 'jamfselfservice://content?entity=policy&id=[POLICY_ID]&action=execute'` where the policy is set to run an inventory update or policy check-in on demand. 

We often have Macs that just stop checking in or updating inventory with no clear reason why. Hoping something like this could help correct these problems.

**Comment by martinvandiemen** [comment]
Appreciate the feedback but this is something very specific to an issue that's related to your environment. Don't expect this to be addressed (soon).
