### ISSUE TITLE
Feature request - Autopkg recipe

### ISSUE THREAD

**Issue by xirianlight** [root3nl/SupportApp#4]
Congrats on your first release update! Out of abject curiosity, do you have plans for creating an Autopkg recipe so users of this app can get automatic downloads/notifications of your posted updates? I'm a user of [Autopkgr](https://github.com/lindegroup/autopkgr) and have my recipes set to run weekly, making sure I don't miss anything.

**Comment by jazzace** [comment]
It looks like a member of the community has now created these:

https://github.com/autopkg/paul-cossey-recipes/tree/master/Support

**Comment by apizz** [comment]
Yep, in that case I think this can be closed

**Comment by martinvandiemen** [comment]
@jazzace, thanks for sharing!
