### ISSUE TITLE
Issue:   Installer erroring out on Monterey 12.0.1

### ISSUE THREAD

**Issue by tranziq** [root3nl/SupportApp#40]
Installation failed. The installer reported: installer: Package name is Support.2.3
installer: Installing at base path /
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “Support.2.3.pkg”.)

**Comment by martinvandiemen** [comment]
We need to improve the postinstall script which causes this issue. The error can be ignored since the app will launch correctly. We will fix this shortly.

**Comment by jordywitteman** [comment]
Hi @tranziq, we've updated the postinstall script with an additional check when no use is logged in. Could you try again?
