### ISSUE TITLE
Missing SF Symbols

### ISSUE THREAD

**Issue by blockcham** [root3nl/SupportApp#56]
I am seeing this issue on a couple my deployments, where symbols just never show up as pictured.  
<img width="140" alt="image" src="https://user-images.githubusercontent.com/4495434/160026162-d31dce77-2009-4654-9ad2-2832ad20fc73.png">

<img width="141" alt="image" src="https://user-images.githubusercontent.com/4495434/160026297-405f616e-6825-4192-b144-b5610d72e4aa.png">

I've tried to reinstall the Support.app but not a full removal and then reinstall so I will try that next.

**Comment by jordywitteman** [comment]
Hi @blockcham could you share the macOS version and SF Symbol name?

**Comment by blockcham** [comment]
@jordywitteman for Support its the First Row Left - person.2.wave.2, Mac Q&A is First Row Right - rectangle.3.group.bubble.left.  Tried with both 2.3 and 2.3.1 for this particular user.  Most everyone else is functioning fine, here is what it looks like for me 
<img width="394" alt="image" src="https://user-images.githubusercontent.com/4495434/160150326-75f8cecb-99f0-440a-b1c3-277455648c15.png">

**Comment by martinvandiemen** [comment]
This could be related to the macOS version. SF Symbols 2 (macOS 11.x) vs SF Symbols 3 (macOS 12.x). person.2.wave.2 and rectangle.3.group.bubble.left are only available in macoS 12.0 or later. Can you check if you're using the same macOS (major) version?

**Comment by blockcham** [comment]
🤦  that user is on 11.6.5 which so that totally makes sense.  Will try again and confirm, thanks.

**Comment by blockcham** [comment]
Confirmed went back to SF Symbols 2 and showed up on macOS 11.x fine.  Thanks!
