### ISSUE TITLE
Feature Request - LastBackup (Retrospect)

### ISSUE THREAD

**Issue by captain-lungo** [root3nl/SupportApp#58]
It would be great to have a reading of the last successful Retrospect backup.
Just like the uptime.

**Comment by jordywitteman** [comment]
Hi @captain-lungo we're working on a model where you can publish the output of your own commands/scripts to a button/tile, similar to an Extension Attribute in Jamf Pro. This will allow the app to be generic and provide unlimited possibilities. Please track this issue: https://github.com/root3nl/SupportApp/issues/34
