### ISSUE TITLE
MacMini: en0 (Ethernet) displayed as WiFi with Unknown SSID

### ISSUE THREAD

**Issue by meta-github** [root3nl/SupportApp#69]
The app (v2.4) displays the right IP on a system where en0 is not a Wi-Fi (this is the case e.g. on MacMini 2018, but also on MacPro), but it is using the wrong icon and shows "Unknown SSID".

**Comment by rougegoat** [comment]
Verified this is happening on a few machines in our test setup as well.

**Comment by jordywitteman** [comment]
@meta-github @rougegoat we think this should now be resolved in v2.4.1 where there is an additional check what the wireless interface is instead of assuming en0 is wireless.
