### ISSUE TITLE
Add into Sample Profile  demo of new Support Extensions 

### ISSUE THREAD

**Issue by trekkim** [root3nl/SupportApp#73]
Hi, it is not issue directly but I would like to ask if will be possible  add an example with integrated New Support Extensions in to MDM Profile. 

Thank you

**Comment by jordywitteman** [comment]
Hi @trekkim thank you I just updated the example profile and some documentation. Hopefully this will help you make it work!

**Comment by trekkim** [comment]
Hi @jordywitteman , thank you that is great, I have one more question, if I wanna add battery condition,

<key>ExtensionLinkA</key>
								<string>defaults write /Library/Preferences/nl.root3.support.plist ExtensionLoadingA -bool true; /usr/local/bin/battery_condition.zsh</string>
								<key>ExtensionSymbolA</key>
								<string>battery.75</string>
								<key>ExtensionTitleA</key>
								<string>Battery Condition</string>
								<key>ExtensionTypeA</key>
								<string>DistributedNotification</string>
								<key>FirstRowLinkLeft</key>
								<string>com.teamviewer.TeamViewer</string>
								<key>FirstRowLinkMiddle</key>
								<string>https://support.root3.nl</string>
								<key>FirstRowLinkRight</key>
								<string>com.jamfsoftware.selfservice.mac</string>
								<key>FirstRowSubtitleLeft</key>
								<string>Share your screen</string>
								<key>FirstRowSubtitleMiddle</key>
								<string>Now</string>
								<key>FirstRowSubtitleRight</key>
								<string>Download Apps</string>
								<key>FirstRowSymbolLeft</key>
								<string>cursorarrow.and.square.on.square.dashed</string>
								<key>FirstRowSymbolMiddle</key>
								<string>lifepreserver</string>
								<key>FirstRowSymbolRight</key>
								<string>cart.badge.plus</string>
								<key>FirstRowTitleLeft</key>
								<string>Remote Support</string>
								<key>FirstRowTitleMiddle</key>
								<string>Get Support</string>
								<key>FirstRowTitleRight</key>
								<string>Self Service</string>
								<key>FirstRowTypeLeft</key>
								<string>App</string>
								<key>FirstRowTypeMiddle</key>
								<string>URL</string>
								<key>FirstRowTypeRight</key>
								<string>App</string>
								<key>FooterText</key>
								<string>Provided by your **IT department** with ❤️</string>
								<key>HideFirstRow</key>
								<false/>
								<key>HideSecondRow</key>
								<true/>
								<key>InfoItemFive</key>
								<string>Password</string>
								<key>InfoItemSix</key>
								<string>ExtensionA</string>
								<key>Logo</key>
								<string>/Library/Application Support/JAMF/swift-64x64_2x.png</string>
								<key>NotificationIcon</key>
								<string>/Library/Application Support/JAMF/swift-64x64_2x.png</string>
								<key>OnAppearAction</key>
								<string>/usr/local/bin/battery_condition.zsh</string>
								<key>PasswordExpiryLimit</key>
								<integer>14</integer>
								<key>PasswordLabel</key>
								<string>Cloud Password</string>
								<key>PasswordType</key>
								<string>KerberosSSO</string>
								<key>ShowWelcomeScreen</key>
								<true/>
								<key>StatusBarIconNotifierEnabled</key>
								<true/>
								<key>StorageLimit</key>
								<integer>90</integer>
								<key>Title</key>
								<string>Hello **Support App** 2.4</string>
								<key>UptimeDaysLimit</key>
								<integer>21</integer>


does not work for me , do I still missing something , thx for help here.
