### ISSUE TITLE
getModelIdentifier and getModelName not detecting the 2022 MacBook Pro (13-inch, M2)

### ISSUE THREAD

**Issue by johngsea** [root3nl/SupportApp#76]
Computer model Identifier prefix changes by Apple has caused some issues:

The model identifier for MacBook Pro (13-inch, M2, 2022) is “Mac14,7”
Note Apple has removed "MacBook" prefix from the model IDs (going forward?)

ComputerInfo.Swift, 
func getModelIdentifier() {
// ...
// ~line 269:
if modelIdentifierString.hasPrefix("MacBook") { 
            computerNameIcon = "laptopcomputer"
        }
        
        func getModelName() {
//... another problem here:
        } else if modelIdentifierString.hasPrefix("MacBookPro") {
            self.modelShortName = "MacBook Pro"
            
        
        see Mactracker app for more details on that model:
        https://apps.apple.com/us/app/mactracker/id430255202?mt=12

**Comment by jordywitteman** [comment]
Hi @johngsea yes indeed this is an issue we're trying to solve. Seems like it is not possible anymore to get the model from the Model Identifier as it becomes generic. We are seeing the same behaviour on the M2 Air. Ideas are welcome!

**Comment by johngsea** [comment]
Thank you! We'll give it some thought over here, too.

**Comment by nider** [comment]
This can be obtained on Apple Silicon Mac hardware from the IO Registry
```shell
ioreg -l -c IOPlatformDevice | grep -e \"product-name\" -e \"product-description\"
```

**Comment by jordywitteman** [comment]
Thanks @nider! I tested earlier with another command but that didn't work due to sandboxing, but this one does! Will work one this to implement in 2.4.1

**Comment by jordywitteman** [comment]
This was added to 2.4.1 and we can now get the right icon and model name for all Apple Silicon devices. Thanks again!
