### ISSUE TITLE
Installation error via MDM

### ISSUE THREAD

**Issue by akiralight** [root3nl/SupportApp#77]
Unable to distribute installer (PKG) through MDM "Mobileiron". I get "Support.2.4.pkg: Unrecognized file format" error when I add PKG file. Other PKGs (for example Firefox) are added correctly. Installing manually on a Mac is also correct. It looks like there is a problem with the PKG that does not allow it to be installed through some MDM systems.

**Comment by jordywitteman** [comment]
@akiralight is this still happening with v2.4.2? Is this MobileIron Cloud or Core?

**Comment by jordywitteman** [comment]
Hi @akiralight we may have identified the issue. The pkg for 2.4.2 (revised version) is now a distribution package which is required when MDM solutions install packages using an MDM command like `InstallApplication`. Could you try again?
