### ISSUE TITLE
JSON schema for Jamf Pro - FooterText Emoji not working

### ISSUE THREAD

**Issue by opus-nbo** [root3nl/SupportApp#78]
When I enter a emoji (💙 ) in the field for FooterText in Jamf Pro using the JSON schema, it get's saved as '?' and is displayed as same in the SupportApp itself. 

Markdown emoji does also not work and is displayed as `:blue_heart:` in the App.

App is running on 12.5 Monterey.

**Comment by everetteallen** [comment]
@opus-nbo I have the same issue.  As a workaround I was able to paste the emoji in after loading the JSON manifest into Jamf and filling in the blank

**Comment by opus-nbo** [comment]
@everetteallen I did the same, loaded the JSON and added the emoji to the blank field for "Footer Text" but the emoji is displayed as "?" in the App.

**Comment by everetteallen** [comment]
One other thing I found is that is the emoji is before any other text it will not display (ie at the beginning of the sentence)

**Comment by opus-nbo** [comment]
For me, it's at the end of the sentence where it not works. strangely, the ❤️  `:heart:` works, but not the 💙  `:blue_heart:`

**Comment by cubandave** [comment]
This is likely a bug/lack of support in the MDM not supporting the Unicode variants in their databases. If you do a default write locally it might work. Report it to your MDM provider if that’s the case.

**Comment by cubandave** [comment]
Funny… cuz I ran into the same thing wanting to load a pink heart.

**Comment by everetteallen** [comment]
I am able to to copy the actual character like from the keyboard view app and paste into the manifest and both red and blue heart work so not sure if the MDM is as fault here.

**Comment by opus-nbo** [comment]
What do you mean by 'keyboard view app'? I copied it from the emoji popup, I think it's called 'Character Viewer'. This way it did not work.

**Comment by bradtchapman** [comment]
@opus-nbo : this is a Jamf limitation, not anything to do with Support app.  The input field automatically converts some characters into ? or empty blocks.  File a bug with Jamf.

Recommending this be closed.
