### ISSUE TITLE
Command examples?

### ISSUE THREAD

**Issue by apizz** [root3nl/SupportApp#8]
Preferences like `FirstRowTypeLeft` have either a value of App, URL, or Command.  However, the related `FirstRowLinkLeft` preference only every shows examples for Apps or URLs to open.  The description seems to indicate only support for Apps or URLs:

>The Bundle Identifier of the app or link that should be opened.

Is `Command` in fact a supported value, and if so can the documentation reflect this?  Examples would also be helpful.

**Comment by apizz** [comment]
NVM I missed https://github.com/root3nl/SupportApp#app-link-or-command-shortcuts

**Comment by boettchs** [comment]
HI, love the app!  One small thing - the "Last reboot" button shows "5 hour since last reboot" as opposed to "5 hours since last reboot".  Could this be added to upcoming fixes?
Thank you!
