### ISSUE TITLE
Update SupportHelper for Ventura

### ISSUE THREAD

**Issue by johngsea** [root3nl/SupportApp#80]
Hi - It looks like this could be relevant. If not, please ignore. Thanks!

"Prior to macOS 13, part of the application-design process of helper executables included scripts that installed one or more property lists into specific directories based on the type of service, such as the following locations of property lists:

$HOME/Library/LaunchAgents
/Library/LaunchAgents
/Library/LaunchDaemons"

"In macOS 13 and later, a new structure in the app bundle simplifies the installation of these login items and associated property lists. This new structure allows you to keep helper app resources inside the app’s bundle,"

https://developer.apple.com/documentation/servicemanagement/updating_helper_executables_from_earlier_versions_of_macos

**Comment by jordywitteman** [comment]
Hi @johngsea we are looking into this, but currently only for the LaunchAgent for the main app to avoid using a postinstall script in the install package where the LaunchAgent is created. We actually already worked this out in another [branch](https://github.com/root3nl/SupportApp/tree/SMAppService). 

Interesting idea to also do this with SupportHelper and package it within the main app's bundle. Thanks for bringing it up!

**Comment by bradtchapman** [comment]
@jordywitteman : SupportHelper is working in Ventura using SupportApp 2.4.3.
