### ISSUE TITLE
EA app items show progress bar

### ISSUE THREAD

**Issue by cwmcbrewster** [root3nl/SupportApp#81]
App/URL Extension Attribute items show a blank progress bar. It would be nice if App/URL items didn't have a progress bar and looked just like the other App and URL items.
![Screen Shot 2022-08-22 at 9 39 54 AM](https://user-images.githubusercontent.com/43007934/185973968-39c6fadf-6b85-4f98-a59b-b4a800e71026.png)
.

**Comment by jordywitteman** [comment]
Hi @cwmcbrewster this is not a progress bar but a text placeholder. This placeholder is shown until a value is written to either `ExtensionValueA` or `ExtensionValueB` in `/Library/Preferences/nl.root3.support.plist`. There are some examples available here: https://github.com/root3nl/SupportApp#how-to-populate-support-app-extensions

Does this answer your question?

**Comment by cwmcbrewster** [comment]
Thanks for the response. That helps. I guess my question then is, Is there a way to just turn the text placeholder off completely for an EA item?
