### ISSUE TITLE
unable to use $FULLNAME!

### ISSUE THREAD

**Issue by GitSweetDragon** [root3nl/SupportApp#87]
Hello Team,
I tried several solutions, but I couldn't get the Set title to "Hi $FULLNAME!" variable to work and show current user. 
the text just looks like this on macs : "Hi $FULLNAME!"

Anything about "user" not working 

With $FULLNAME => Appear $FULLNAME
With $REALNAME or $USERNAME+> nothing Appear

But if i user computer variable, it's work. 

In "xxx.jamfcloud.com/computers.html?id=2&o=r"

In Global managemant i can see : 
Last User: is set correctly with firstname.lastname
But : 
Jamf Connect - UserLoginName:  Does not exist
Jamf Connect - LastSignIn:Does not exist

In Local User Accounts i can see : 

USERNAME & FULL NAME correctly set 

Thanks for your help

EDIT 12 October 2022 : AFTER 5 DAYS  and this POST somethings strange append, now it's work !!! 
i don't understund.

EDIT 13 October 2022 : i REOPEN the issue, after erase and start over the mac, when SUpport app and policie finish deploy i get "Hello **!** for Hello **$REALNAME** 

:(

EDIT 14 October 2022 :  

Hello Again, 

Something interesting discovered!

If you go to [Computers] : https://acme.jamfcloud.com/computers.html?id=5&o=r&v=inventory
Then in "User and Location"
And that you fill in All the information and that you save, then that in username you put only the first name (just delet and without accent).
When you then put the value Hello $USERNAME
you get the result with just the first name in small caps

**Comment by martinvandiemen** [comment]
We're not seeing this experience at all. This must be something within your environment. Please read the documentation or reach out to Slack MacAdmin for support.

**Comment by GitSweetDragon** [comment]
Hello @martinvandiemen how can i join macadmins please ? 
it's said "Ask the workspace administrator of the MacAdmins team to invite you".
i tried to create one with my gitlab id gitsweetdragon@macadmins.org but don't know where it goes :(
