### ISSUE TITLE
build failed due to SMAppService

### ISSUE THREAD

**Issue by meta-github** [root3nl/SupportApp#88]
Hi,

while trying to compile v2.4.1 using Xcode-14.0.1 on Ventura beta 11, the build fails with
Cannot find 'SMAppService' in scope

in file AppDelegate.swift, line 407.

I guess that I am doing something wrong and I need some help. We are using that app with a few local modifications, so being able to compile the app is necessary for us.

Thanks!

**Comment by jordywitteman** [comment]
Hi @meta-github currently you'll Xcode 14.1 with support for macOS 13. Xcode 14.0.1 does not contain the required SDK/framework for SMAppService to compile.
