### ISSUE TITLE
macOS 13: no notification in menu icon

### ISSUE THREAD

**Issue by meta-github** [root3nl/SupportApp#89]
Hello,

tested with v2.4.1 on macOS Ventura beta 11 (and a slightly older beta): if a user password is about to expire or if a system update is available, the notification is correctly shown in the application window after the user has clicked on the menu icon to open the application. The menu icon itself does not show the notification. On macOS Monterey, the same configuration works correctly.

Is there anything I can do to help to resolve this issue (log files, etc.)?

Thanks

- meta

**Comment by jordywitteman** [comment]
Hi @meta-github a fix for this is already identified and scheduled for 2.4.2 which should launch before macOS 13 is released. If you want to compile/test now, the fix is in the development branch!

**Comment by meta-github** [comment]
Thanks a great lot! After copying AppDelegate.swift and Views/StatusItemBadgeView.swift from the development branch, the notifications now work again on Ventura.

**Comment by jordywitteman** [comment]
Great, glad to help!
