### ISSUE TITLE
Make custom menubar icon scale.

### ISSUE THREAD

**Issue by Bretterteig** [root3nl/SupportApp#91]
Not sure if feature request or bug. I just started testing SupportApp with 2.4.1:

We want to use a custom menubar icon for the support app. 
Currently you can only add an icon that is 16x16px as others would not be scaled to fit in the menubar constraints.
Scaling our icon to size is not desirable however as it becomes a blurry mess. 
With Jamf Connect we have been able to use a larger (64x64px) icon that is way sharper when scaled.

Tested on an M1 16" MacBook Pro

**Comment by martinvandiemen** [comment]
Please note it's 16 points not pixels: https://github.com/root3nl/SupportApp#configuration. You should also increase your DPI to create a scharp icon.
