### ISSUE TITLE
Feature Request: Key to trigger Notification badge on Extension A/B

### ISSUE THREAD

**Issue by jaedwards24** [root3nl/SupportApp#94]
Please add an option to display a notification badge on Extension A or B based on whatever condition is determined in the OnAppearAction script. This notification badge should display on the Extension A or B tile as well as on the menu bar icon.

**Comment by jordywitteman** [comment]
Will be added in v2.5

**Comment by jordywitteman** [comment]
You can now set `ExtensionAlertA` or `ExtensionAlertB` to `true` to trigger a warning in the extension and menu bar icon. An example is here: https://github.com/root3nl/SupportApp#how-to-populate-support-app-extensions
