### ISSUE TITLE
Footer text in darkmode 

### ISSUE THREAD

**Issue by Stephan-root** [root3nl/SupportApp#99]
Currently is the Footer text in darkmode black. Would be nice to make it white on dark mode detection.
<img width="319" alt="Screenshot 2022-11-28 at 11 16 33" src="https://user-images.githubusercontent.com/59468142/204253355-670e44b3-b790-476f-8b8f-d1b12597cb55.png">

**Comment by bradtchapman** [comment]
Duped by #109 .  @jordywitteman can this be closed?  It sounds like it's already planned for released.

**Comment by jordywitteman** [comment]
The `FooterText` provides better contrast since v2.5 and should be easier to read
